### PR TITLE
superfence for mkdocs

### PR DESCRIPTION
**Pull request by davy39**
Hi,
Finally I did implement a `superfence` attribute  to adapt the `markdownBlock` to be used with [pymdownx.superfences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) with [mkdocs](https://www.mkdocs.org/) and the [custom fence](https://mkdocs-logic.forge.apps.education.fr/) I've developped.

Do you think that it could be merge ?
This way, I can modify my custom fence to rebuild the bundle when you make changes ?

Thanks again for your work !

### CODE REVIEW

**Comment by davy39** [comment]
See [https://gitlab.com/logic-superfence/logic-superfence](https://gitlab.com/logic-superfence/logic-superfence) if interested on how it looks on mkdocs (doesn't include this change on the bundle yet).

**Comment by jppellet** [comment]
Hey, thanks a lot for your contribution! I was thinking to try to future-proof it a bit… Would it be OK with you if instead of having `superfence` as attribute, we have something like `exportformat="superfence"`?

This would allow more values in the future, should someone want another format.

**Comment by davy39** [comment]
You're absolutely right. I've made some modifications in my code.

**Comment by jppellet** [comment]
Great! I'll merge it and adapt a little bit to fall back to "myst" in case of invalid format value. Thanks!

**Comment by davy39** [comment]
Perfect, I've scheduled a check on your changes to update my package.
Thanks again !

**Comment by jppellet** [comment]
Great! You're most welcome!

**Pull request merged**
